# Generated by Django 5.1.4 on 2024-12-13 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BlogTitle', models.CharField(max_length=50)),
                ('BlogContent', models.CharField(max_length=200)),
                ('BlogImage', models.CharField(max_length=50)),
                ('BlogCreateDate', models.DateTimeField()),
            ],
        ),
    ]
