# Generated by Django 5.1.4 on 2024-12-15 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_alter_blog_blogcontent_alter_blog_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='BlogContent',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='blog',
            name='BlogImage',
            field=models.ImageField(upload_to='blogs'),
        ),
    ]
