# Generated by Django 5.1.4 on 2024-12-15 14:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_writer_blog_writer'),
    ]

    operations = [
        migrations.AddField(
            model_name='writer',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='writer',
            name='last_login',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
