# Generated by Django 5.1.4 on 2024-12-16 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_writer_is_active_writer_last_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='writer',
            name='WriterAbout',
        ),
        migrations.RemoveField(
            model_name='writer',
            name='WriterImage',
        ),
        migrations.AlterField(
            model_name='writer',
            name='WriterMail',
            field=models.EmailField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='writer',
            name='WriterName',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
