# Generated by Django 5.1.4 on 2024-12-17 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0011_alter_blog_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='writer',
            name='WriterAbout',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='writer',
            name='WriterImage',
            field=models.ImageField(null=True, upload_to='writer'),
        ),
    ]
